### ISSUE TITLE
Pulling text from all channels that contain a certain keyword

### ISSUE THREAD

**Issue by lpatmo** [AlexeyMK/hp-photos-from-slack#2]
Hello! Thanks for publishing your project. I'm trying to figure out how to tweak it so that I'm publishing ANY message from ANY channel that contains a certain keyword (a hashtag #todayilearned).   

In settings.json, however, if I remove the channel token ID from the NAME_OF_SLACK dictionary, the app breaks. 

In server/main.coffee, I added a variable named `message_texts` that pushes all texts to the array m:

```
message_texts = (m for m in messages)
      console.log(message_texts)
      for text in message_texts
        console.log "found a text: #{text.text}" 
        Photos.upsert({uid},
                      {uid, text: text, batch:batch})
```

I'm not too familiar with coffeescript, so I'm trying to figure out how to add in an `if` statement somewhere around `message_texts = (m for m in messages)` so that the coffeescript renders into javascript that looks like this:

```
 m = messages[i];
      if (m.indexOf('todayilearned') > -1) {
        results.push(m);
      }
```

Any thoughts/help would be appreciated!

Thanks,
Linda

**Comment by AlexeyMK** [comment]
If you're forking the project and are more comfortable with javascript, you may want to go to http://js2.coffee/ and convert the individual files to JS.

Looking at the [Slack API](https://api.slack.com/outgoing-webhooks), your use case seems quite doable, if you replace the channel name with trigger words. It'll require a bit of engineering work, but doesn't seem too onerous. Curious to hear how it goes!

**Comment by lpatmo** [comment]
Thanks for responding! Yeah, I'll probably convert all the coffeescript files to JS and see how it goes.

One thing I was a little confused about was the fact that in your README.md the slack token ID you had us grab began with `xoxp-`. Meanwhile (maybe this is a new Slack update?) the integration page for setting up a new outgoing webhook seems to let us set up a scenario that has it doing the busywork of watching "ALL" channels with a certain triggerword -- i.e. I don't have to write any code to parse out the specific data I need (all messages from any channel containing the trigger word #todayilearned). But the token ID looks different, as you can see below.

![screen shot 2015-12-13 at 5 22 36 pm](https://cloud.githubusercontent.com/assets/4512699/11770924/5c2fe4c0-a1be-11e5-8afa-a3044070da24.jpg)

Your repo is the first I found of a working example connecting Slack's outgoing webhook with Meteor (thank you!); wish there were more official examples.

Anyway, will report back if I find a good solution.

**Comment by AlexeyMK** [comment]
Linda - the token in the webhook is not as important (it's only used to
verify that the webhook really came from slack - I don't bother to check,
because I don't think my slack channel is worth attacking (though, PRs are
welcome).

The `xoxp-` token is one you'll need for making web API calls, instead. I
think you'll still need it, and change the webhook to follow to, probably,
https://api.slack.com/methods/search.files.

Alexey

**Comment by lpatmo** [comment]
Belated update: I realized eventually that I could just use the web API, and an outgoing webhook was not that important for what I needed to do. This is the end result: http://codebuddies.org/todayilearned

Anyway, thanks for responding a few weeks ago. Will close this issue now. :)
